# Generated by Django 4.2.4 on 2023-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nodisplay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
