# Generated by Django 4.2.4 on 2023-11-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_display_post_nodisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='display',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nodisplay',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
