# Generated by Django 4.2.4 on 2023-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_display_remove_post_nodisplay_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
